{% set name = "pypinfo" %}
{% set version = "21.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypinfo-{{ version }}.tar.gz
  sha256: 4a500a989977de2f2ea2b05e4d84a5a0caef7d43dffbe40ab581cbf60cc78293

build:
  entry_points:
    - pypinfo = pypinfo.cli:pypinfo
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - binary
    - click
    - google-cloud-bigquery-core >=2.11.0
    - packaging >=16.2
    - platformdirs
    - tinydb >=4
    - tinyrecord >=0.2.0

test:
  imports:
    - pypinfo
  commands:
    - pip check
    - pypinfo --help
  requires:
    - pip

about:
  summary: View PyPI download statistics with ease.
  home: https://github.com/ofek/pypinfo
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
